when:
    changeset: ## when PR contains any of those entries in the changeset
        - "filebeat/**"
        - "@ci" ## special token regarding the changeset for the ci
        - "@oss" ## special token regarding the changeset for the oss
stages:
    # default stage - it runs always for:
    #   - branches/tags
    #   - on PRs
    #   - GitHub comment /test filebeat
    #   - GitHub label filebeat
    mandatory:
        # NOTE: stage name should be unique!
        unitTest:
            command: ".buildkite/filebeat/scripts/unit-tests.sh"
            platform: "family/platform-ingest-beats-ubuntu-2204"
        crosscompile:
            command: ".buildkite/filebeat/scripts/crosscompile.sh"
            platform: "family/platform-ingest-beats-ubuntu-2204"
        goIntegTest:
            command: ".buildkite/filebeat/scripts/integration-gotests.sh"
            platform: "family/platform-ingest-beats-ubuntu-2204"
        pythonIntegTest:
            command: ".buildkite/filebeat/scripts/integration-pytests.sh"
            platform: "family/platform-ingest-beats-ubuntu-2204"
        rhel-9:
            command: ".buildkite/filebeat/scripts/unit-tests.sh"
            platform: "family/platform-ingest-beats-rhel-9"
        unitTest-windows-2022:
            command: ".buildkite/filebeat/scripts/unit-tests-win.ps1"
            platform: "family/platform-ingest-beats-windows-2022"
        unitTest-windows-2016:
            command: ".buildkite/filebeat/scripts/unit-tests-win.ps1"
            platform: "family/platform-ingest-beats-windows-2016"
    # optional stage - it runs on:
    #   - branches/tags
    #   - on PRs if:
    #       - GitHub comment /test filebeat <sub-stage-name> . i.e: /test filebeat integTest
    #       - GitHub label <sub-stage-name> . i.e: integTest or unitTest-arm or unitTest-macos ...
    extended:
        unitTest-arm:
            command: ".buildkite/filebeat/scripts/unit-tests.sh"
            platform: "core-ubuntu-2004-aarch64"
        unitTest-macos:
            command: ".buildkite/filebeat/scripts/unit-tests.sh"
            platform: "generic-13-ventura-x64"
        unitTest-windows-2019:
            command: ".buildkite/filebeat/scripts/unit-tests-win.ps1"
            platform: "family/platform-ingest-beats-windows-2019"
