# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: "Generate dynamic pipeline"
    command: ".buildkite/scripts/generate_pipeline.sh"
    agents:
      provider: "gcp"
      image: "family/platform-ingest-beats-ubuntu-2204"
